### ISSUE TITLE
Some MythicMobs attributes not included in recipe output

### ISSUE THREAD

**Issue by EHAndrew** [mcgrizzz/ProRecipes#40]
ProRecipes 1.13 build created by Anonymous_Dr in the Spigot Discussion forum for the plugin
Spigot 1.13.2
MythicMobs Dev Build 2586

This is what the item should be, as spawned in by MythicMobs: [Imgur Link - MythicMobs Item](https://i.imgur.com/nLeU2RV.png)
This is what the item is when processed by ProRecipes: [Imgur Link - ProRecipes Item](https://i.imgur.com/Wn7ULOv.png)

And here's the config for the MM item:
```
AncientChestplate:
  Id: iron_chestplate
  Data: 0
  Display: '&8Ancient Chestplate'
  Lore:
  - '&6Very old, very heavy,'
  - '&6very tough!'
  - ''
  - '&d+3000 Armor'
  - '&d+100 Critical Strike'
  Enchantments:
  - DURABILITY:10
  Attributes:
    Chest:
      KnockbackResistance: 0.2
      MovementSpeed: -0.15
```
